import type { Metadata } from "next";

import { ThemeProvider } from '@/contexts/theme-context'

import "./globals.css";

import React from 'react'


export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const customTheme = {
  backgroundColor: 'black',
  fontFamily: 'Consolas, "Courier New", Courier, monospace',
  fontSize: '14px',
  textColor: '#00ff00',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ThemeProvider theme={customTheme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
